### ISSUE TITLE
Preparation for series A funding - listing on CEX and DEX

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/series-a#11]
We may use listing on one or more CEX and DEX to attract VC attention.

During the card issuance research, I contacted various potential partners.
Among them are listing managers of crypto.com, MEXC, and others.

**Comment by 0x4007** [comment]
Listing on DEX we don't need to plan for, we just do it. CEX I don't want to pay for any listings. However in Korea we have a lot of relationships with CEXes so if we can get a good deal we might consider it.
