### ISSUE TITLE
Preparation for series A funding - run a Galxe campaign for developers 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/series-a#3]
This is a draft not ready for review

Galxe and similar solutions are common tools for community engagement. 
We can create a campaign where tasks will be related to code review, comments, tasks on GitHub. 

Overview
https://galxe.com/passport
https://galxe.com/protocol
https://docs.galxe.com/protocol/introduction

Cooperation
https://galxe.com/createspace
https://help.galxe.com/en/articles/8506982-permissionless-space-creation-a-user-friendly-guide
https://help.galxe.com/en/articles/7329021-campaign-creation-made-easy-breaking-down-the-process-into-three-simple-steps
Campaign TBD 

The list of the top solutions
https://galxe.com/
https://www.intract.io/
https://layer3.xyz/
https://zealy.io/
https://business.questn.com/
https://taskon.xyz/
TBD

**Comment by sergfeldman** [comment]
@pavlovcik ChainGPT used Galxe and currently has 371K followers there https://galxe.com/ChainGPT

**Comment by 0x4007** [comment]
If its simple to set up then we can consider this
