### ISSUE TITLE
Preparation for series A funding - cooperate with Electric Capital 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/series-a#5]
Electric Capital is a VC that provides a regular Crypto Developer Report
https://www.developerreport.com/developer-report

According to their data as of DEC-31-2023
https://www.developerreport.com/

>We fingerprinted 485 million code commits across 818k open-source repositories to create this year's Developer Report

>6,889 FULL-TIME DEVS
22,411 MONTHLY ACTIVE DEVS
351,836 TOTAL REPOS
211,392,146 TOTAL COMMITS

Ubiquity can propose cooperation with Electric Capital
- Use their data
- Contribute to the data collection
- Organize the retrodrop for crypto developers together with Electric Capital
- More ideas can be brainstormed

**Comment by 0x4007** [comment]
> Organize the retrodrop for crypto developers together with Electric Capital

Could be interesting for marketing purposes if we drop an NFT or something.

**Comment by 0x4007** [comment]
I think this task could be just for outreach purposes.
