### ISSUE TITLE
Preparation for series A funding - initiate DAO research institute

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/series-a#6]
VCs consider a potential of a project before investing.
Contribution to ecosystem research and public goods can be considered as signs of a fundamental approach and high potential.

Ubiquity can initiate the DAO research institute
- Engage Maker DAO and other well established DAOs for contribution to the DAO research
- Define research programs with grants in the areas of autonomous operations, AI for development, decentralized decision making, etc
- Compile a DAO assessment checklist 
- TBD

One of the research programs can be dedicated to automated Open Source development like UbiquiBot performs.
Cooperation with some DAOs can start from the participation in the research, and continue with using the UbiquiBot.

**Comment by 0x4007** [comment]
I think this might be spreading ourselves too thin. Its a large undertaking and the benefits aren't immediately obvious to me.
